services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_USER=apluser
      - MYSQL_PASSWORD=apluserpass
      - MYSQL_DATABASE=apldb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  hardhat-network:
    build:
      context: .
      dockerfile: tests/Dockerfile_hardhat
    ports:
      - "8545:8545"
  ibet-wallet-api-postgres:
    image: ibet-wallet-api
    build:
      context: ./
      dockerfile: ./tests/Dockerfile_unittest
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - TEST_DATABASE_URL=postgresql://apluser:apluserpass@postgres/apldb
      - UNIT_TEST_MODE=1
      - RESPONSE_VALIDATION_MODE=1
      - BOND_TOKEN_ENABLED=1
      - MEMBERSHIP_TOKEN_ENABLED=1
      - COUPON_TOKEN_ENABLED=1
      - SHARE_TOKEN_ENABLED=1
    links:
      - postgres:postgres
      - hardhat-network:quorum
    depends_on:
      - postgres
      - hardhat-network
    volumes:
      - ./cov:/app/ibet-Wallet-API/cov
  ibet-wallet-api-mysql:
    image: ibet-wallet-api
    build:
      context: ./
      dockerfile: ./tests/Dockerfile_unittest
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - TEST_DATABASE_URL=mysql+pymysql://apluser:apluserpass@mysql:3306/apldb
      - UNIT_TEST_MODE=1
      - RESPONSE_VALIDATION_MODE=1
      - BOND_TOKEN_ENABLED=1
      - MEMBERSHIP_TOKEN_ENABLED=1
      - COUPON_TOKEN_ENABLED=1
      - SHARE_TOKEN_ENABLED=1
    links:
      - mysql:mysql
      - hardhat-network:quorum
    depends_on:
      - mysql
      - hardhat-network
    volumes:
      - ./cov:/app/ibet-Wallet-API/cov