version: "3"

services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=apluser
      - MYSQL_PASSWORD=apluserpass
      - MYSQL_DATABASE=apldb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ganache:
    image: "trufflesuite/ganache:latest"
    ports:
      - "8545:8545"
    command:
      - -g 0
  ibet-wallet-api-postgres:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - TEST_DATABASE_URL=postgresql://apluser:apluserpass@postgres/apldb
    links:
      - postgres:postgres
      - ganache:quorum
    depends_on:
      - postgres
      - ganache
  ibet-wallet-api-mysql:
    build:
      context: ./
      dockerfile: ./tests/Dockerfile
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - TEST_DATABASE_URL=mysql+pymysql://apluser:apluserpass@mysql:3306/apldb
    links:
      - mysql:mysql
      - ganache:quorum
    depends_on:
      - mysql
      - ganache