version: "3"

services:
  postgres-wallet-api:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
  ganache-cli:
    image: "trufflesuite/ganache-cli:latest"
    ports:
      - "8545:8545"
    command:
      - --gasPrice 0
  ibet-wallet-api:
    build:
      context: ./
      dockerfile: ./app/tests/Dockerfile
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - DATABASE_URL=postgresql://apluser:apluserpass@postgres/apldb
    links:
      - postgres-wallet-api:postgres
      - ganache-cli:quorum
    depends_on:
      - postgres-wallet-api
      - ganache-cli