services:
  postgres:
    image: postgres:17.10@sha256:a426e44bac0b759c95894d68e1a0ac03ecc20b619f498a91aae373bf06d8508d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apluser
      - POSTGRES_PASSWORD=apluserpass
      - POSTGRES_DB=apldb
    tmpfs:
      - /var/lib/postgresql/data
  mysql:
    image: mysql:8.4.10@sha256:d36d39a64cd12a5c1cc9e6aa2bfb5f8d4c81a2f6586e0a04a9ae13939db02209
    environment:
      - MYSQL_USER=apluser
      - MYSQL_PASSWORD=apluserpass
      - MYSQL_DATABASE=apldb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tmpfs:
      - /var/lib/mysql
  anvil-network:
    build:
      context: .
      dockerfile: tests/Dockerfile_anvil
    ports:
      - "8545:8545"
  ibet-wallet-api-postgres:
    image: ibet-wallet-api
    build:
      context: ./
      dockerfile: ./tests/Dockerfile_unittest
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - TEST_DATABASE_URL=postgresql://apluser:apluserpass@postgres/apldb
      - UNIT_TEST_MODE=1
      - RESPONSE_VALIDATION_MODE=1
      - BOND_TOKEN_ENABLED=1
      - MEMBERSHIP_TOKEN_ENABLED=1
      - COUPON_TOKEN_ENABLED=1
      - SHARE_TOKEN_ENABLED=1
    links:
      - postgres:postgres
      - anvil-network:quorum
    depends_on:
      - postgres
      - anvil-network
    volumes:
      - ./cov:/app/ibet-Wallet-API/cov
  ibet-wallet-api-mysql:
    image: ibet-wallet-api
    build:
      context: ./
      dockerfile: ./tests/Dockerfile_unittest
    environment:
      - WEB3_HTTP_PROVIDER=http://quorum:8545
      - RSA_PASSWORD=password
      - TEST_DATABASE_URL=mysql+pymysql://apluser:apluserpass@mysql:3306/apldb
      - UNIT_TEST_MODE=1
      - RESPONSE_VALIDATION_MODE=1
      - BOND_TOKEN_ENABLED=1
      - MEMBERSHIP_TOKEN_ENABLED=1
      - COUPON_TOKEN_ENABLED=1
      - SHARE_TOKEN_ENABLED=1
    links:
      - mysql:mysql
      - anvil-network:quorum
    depends_on:
      - mysql
      - anvil-network
    volumes:
      - ./cov:/app/ibet-Wallet-API/cov
