FROM ghcr.io/foundry-rs/foundry:latest@sha256:0c00cb0bda1ab1b91c9a6bf60f4c76c09c1a8870824b6d4718afbabacf6f9a17

WORKDIR /app/ibet-Wallet-API

COPY tests/run_anvil.sh /app/ibet-Wallet-API/tests/run_anvil.sh

ENTRYPOINT ["bash", "/app/ibet-Wallet-API/tests/run_anvil.sh"]
