FROM ghcr.io/foundry-rs/foundry:latest@sha256:8347b728d5d393dac1c018691b36f506d23b9dcd78341d40ea0fcb11c3a19cdd

WORKDIR /app/ibet-Wallet-API

COPY tests/run_anvil.sh /app/ibet-Wallet-API/tests/run_anvil.sh

ENTRYPOINT ["bash", "/app/ibet-Wallet-API/tests/run_anvil.sh"]
