"""v23.6_feature/alembic

Revision ID: ca8ff8c0c01d
Revises: 1055cb068506
Create Date: 2023-03-30 21:51:38.249506

"""
from alembic import op
import sqlalchemy as sa


from app.database import get_db_schema

# revision identifiers, used by Alembic.
revision = "ca8ff8c0c01d"
down_revision = "1055cb068506"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(sa.text(f"DELETE FROM node WHERE is_synced IS null;"))
    op.alter_column(
        "node",
        "is_synced",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###


def downgrade():
    connection = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node",
        "is_synced",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        schema=get_db_schema(),
    )
    # ### end Alembic commands ###
