name: Pull Request Check
on: [pull_request]

jobs:
  lint-black:
    name: 'Lint check (black)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  unit-test-postgres:
    name: 'Unit tests (PostgreSQL)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run unit test using postgres
        run: docker-compose run ibet-wallet-api-postgres
  unit-test-mysql:
    name: 'Unit tests (MySQL)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run unit test using mysql
        run: docker-compose run ibet-wallet-api-mysql
  migration-test-postgres:
    name: 'Migration tests (PostgreSQL)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run unit test using postgres
        run: docker-compose run ibet-wallet-api-postgres bash --login -c "cd /app/ibet-Wallet-API && make test_migrations"
  migration-test-mysql:
    name: 'Migration tests (MySQL)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run unit test using mysql
        run: docker-compose run ibet-wallet-api-mysql bash --login -c "cd /app/ibet-Wallet-API && make test_migrations"
